cc_binary(
    name = "gen_test_data",
    srcs = ["gen_test_data.cpp"],
    deps = [
        "//fast_ta/src:momentum_backend",
        "//fast_ta/src:volume_backend",
        "//fast_ta/src:volatility_backend",
        "//fast_ta/src:2darray",
        "//fast_ta/src:testing_common",
    ],
)
